set_property IOSTANDARD LVCMOS33 [get_ports {B_OUT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B_OUT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B_OUT[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B_OUT[3]}]
set_property PACKAGE_PIN A3 [get_ports {R_OUT[0]}]
set_property PACKAGE_PIN B4 [get_ports {R_OUT[1]}]
set_property PACKAGE_PIN C5 [get_ports {R_OUT[2]}]
set_property PACKAGE_PIN A4 [get_ports {R_OUT[3]}]
set_property PACKAGE_PIN C6 [get_ports {G_OUT[0]}]
set_property PACKAGE_PIN A5 [get_ports {G_OUT[1]}]
set_property PACKAGE_PIN B6 [get_ports {G_OUT[2]}]
set_property PACKAGE_PIN A6 [get_ports {G_OUT[3]}]
set_property PACKAGE_PIN B7 [get_ports {B_OUT[0]}]
set_property PACKAGE_PIN C7 [get_ports {B_OUT[1]}]
set_property PACKAGE_PIN D7 [get_ports {B_OUT[2]}]
set_property PACKAGE_PIN D8 [get_ports {B_OUT[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G_OUT[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G_OUT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G_OUT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {G_OUT[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R_OUT[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R_OUT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R_OUT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {R_OUT[0]}]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN B11 [get_ports hsync]
set_property PACKAGE_PIN B12 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]

set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]

